### ISSUE TITLE
Install package error

### ISSUE THREAD

**Issue by ericdhkim** [AnnonZerp/pivpn-gui#2]
Hi I am following the install instructions in the readme and after step where I enter the below command into my RPi, I get an error where it seems to not be installing some commands

I run the command:

`sudo apt-get update && sudo apt-get install git apache2 php5 libapache2-mod-php5 php5-mcrypt expect geoip-bin`

Then see this:

`Hit:1 https://deb.nodesource.com/node_12.x buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:4 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libapache2-mod-php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-mcrypt is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5' has no installation candidate
E: Package 'libapache2-mod-php5' has no installation candidate
E: Package 'php5-mcrypt' has no installation candidate`

I thought maybe this was a non-issue, but then when I try to run

`sudo nano /etc/apache2/apache2.conf`

the file is blank

then when I try 
`sudo service apache2 restart`

I see

`Failed to restart apache2.service: Unit apache2.service not found.`

Any ideas what I'm doing wrong? I already have PiVPN (via WireGuard) up and running.

**Comment by bolleyboll** [comment]
Append this to your sources.list(run `sudo nano /etc/apt/sources.list`)

`deb http://mirrordirector.raspbian.org/raspbian jessie main contrib non-free rpi`

Then re-run the command.
