### ISSUE TITLE
on Debian 10

### ISSUE THREAD

**Issue by hdavy2002** [AnnonZerp/pivpn-gui#3]
I am tryin this on  a Debian 10.  Everything is default. I have pivpn installed. 

On the web page it is asking for user name and password. I was confused here.

In apache2.conf, I have the below

# These need to be set in /etc/apache2/envvars
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}

In this case, what should i do?

Thanks

h

**Comment by dpinse** [comment]
User pi
Group pi
